### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by scargill** [dc297/mqttclpro#10]
Hi - we just had a discussion on the Android site - I'm seeing another issue in here about not reconnecting and I'm wondering if they are connected.

So in my situation I have DEBIAN running on the phone - with an MQTT broker - and TASKER talks to the MQTT broker - using your plug in - so that for example from Debian I can send an MQTT message to ring a doorbell using Tasker's access to MP3 files.

All of that works great BUT if you reboot the phone this NEVER works - until you open your App and check settings - so I'm wondering (just a thought)  if Tasker starts BEFORE Debian - so the broker ISN'T READY, your APP tries to connect, fails - and simply does not keep retrying - possibility? That might answer the other issue I noticed about not reconnecting on change of network.

It is absolutely imperative given what people do with Tasker that the connection survives such issues and if it fails - keeps on trying regardless  - I wonder if you could let us know when an update - even an experimental one- is ready to try.

**Comment by dc297** [comment]
Currently, the app does not start automatically on phone boot. I'll add this in the next version.

As far as retrying connection is concerned, the app does that every keep-alive seconds. So maybe reducing keep-alive period will help in this case.

**Comment by scargill** [comment]
Well there’s the problem not starting automatically – BUT I tried adding into TASKER another task to START the app and that didn’t work  -  OK I’ll leave it until you come up with a fix so it starts on phone boot – any idea of timescales? I’m blogging about this (http://tech.scargill.net) and it would be nice to be able to say it works.

**Comment by cinhcet** [comment]
Hi,

first thanks for the app! I use it as a plugin for automate (free tasker alternative)
I have a similar issue: When I reboot and try to publish a message, it does not work until I open the app.

So I also appreciate this feature :-)

If I could help testing or something else, I would be happy

**Comment by fragolinux** [comment]
+1 for me to the request up here... very important that the app would autostart and reconnect broker on phone reboot... thanks in advance :)

**Comment by scargill** [comment]
Any news - when the phone is sitting idling, the MQTT works fine - until a connection break (like rebooting the modem) - it fails every time - I bring the phone to life (press on button) - it says it is waiting for a connection then connects and it is fine then until the next time - as it stands then - not a lot of use - I really would like to see this working reliably.... happy to test...

**Comment by dc297** [comment]
Hey, sorry I had been away on holiday the past week. Came back today only. I'll try to push an update at the earliest.

**Comment by fragolinux** [comment]
thanks :)

2017-04-04 13:15 GMT+02:00 dc297 <notifications@github.com>:

**Comment by scargill** [comment]
Ok, look forward to it. Hope the holiday was a good one.

**Comment by marksev1** [comment]
I have a problem that I don't get any mqtt messages published to my broker? I can see it connecting and disconnecting to the broker, but I don't see any messages being published from the phone to the broker...It almost looks like it "hangs" the broker...What do you think its wrong?

**Comment by dc297** [comment]
Hey @marksev1 
Please share your connection and broker details.

**Comment by marksev1** [comment]
Url: 192.168.88.192 (url of the machine running mqtt broker), do i need to write mqtt://192.168.88.192 ?
Port 1883
username and password i don't have choosen because i have unecrypted currently.
client id i have andro
and keep alive is 1200.
I don't have websockets and ssl enabled.

**Comment by dc297** [comment]
can you share logcat?

**Comment by marksev1** [comment]
Nah, dunno never did that...its probably hard :).. If there is something else i can try before adb debugging I'd try that before.

**Comment by dc297** [comment]
okay, can you try connecting using my other app? https://play.google.com/store/apps/details?id=com.deepeshc.mqttrec

**Comment by scargill** [comment]
Erm, isn’t that the one I’m already using….

**Comment by fragolinux** [comment]
No, I think this is the standalone version, not the Tasker one

Il 05 apr 2017 2:16 PM, "Peter Scargill" <notifications@github.com> ha
scritto:

**Comment by dc297** [comment]
@scargill @fragolinux @cinhcet I have pushed a new update to start app automatically on boot. Please test and let me know your observations.

@marksev1 Let's open a new issue for the problem you are facing. Posting updates on this issue will create confusion.

**Comment by scargill** [comment]
Seems to work!

**Comment by dc297** [comment]
Great! Now let's monitor the connection closely.

**Comment by dc297** [comment]
Hi Guys

Any new observations on this issue?

Cheers

**Comment by fragolinux** [comment]
nope

2017-05-22 11:11 GMT+02:00 dc297 <notifications@github.com>:

**Comment by marksev1** [comment]
I didn't retest it..I might do it again in the coming days...

**Comment by dc297** [comment]
I have closed this issue. Please reopen if any new observations are made.
