### ISSUE TITLE
Control Connection via Tasker

### ISSUE THREAD

**Issue by ShaddyDC** [dc297/mqttclpro#11]
It'd be amazing if we could use Tasker to enable/disable the connection to the server/broker when we want. That'd, for example, allow us to only try to connect whilst being at home. We could also make attempts to reconnect rely on a number of other factors. It's just a lot more flexible than the current keep-alive interval.
Maybe, if we're adventurous, we could even connect to different servers in different locations.
On that note, it'd also be nice to get the current connection state. That'd allow for some decent status checking and notifying the user if something's wrong in a user-defined way.
I feel like that would be a useful and logical extension to the existing functionality.
Thank you for putting time and effort into this project, btw; I really appreciate it!

**Comment by dc297** [comment]
Hey @ShaddyDC 

Seems like a nice idea. Let me make a draft on how to implement it and I'll let you know.

Cheers
Deepesh

**Comment by ShaddyDC** [comment]
Thank you, that'd be amazing! :)

**Comment by dc297** [comment]
Hey so this is what I am planning to implement

1. Give the user ability to send disconnect signal to the app via tasker. Also give a disconnect button in the app.

2. Support multiple brokers. The user will be able to configure multiple brokers in the app and while configuring the action of connecting to broker, they'll be able to choose the broker they want to connect to. **For now, the user will be able to connect to only one broker at a time.**

3. Not sure how to implement the connection status functionality. You got any ideas?

Cheers
Deepesh

**Comment by ShaddyDC** [comment]
That seems good to me.
About the status, I thought about just an action you can execute and it'll give you some variables.
One that contains the current connection status (Connected, Disconnected, Attempting to connect, Failed to Connect, or whatever), and one that contains the currently connected to server, whether it be as address or as connection name, assuming we can name the different brokers we can configure.
If you implement a feature to be connected to multiple brokers at the same time, you might have to return an array, which'd be a bit more cumbersome, but doable. 
Well, I haven't thought about it too much myself, so I can't give you any thought-out solution. This is kinda like autoHue works, or at least how I remember it to work.
Anyway, thank you for your hard work!

**Comment by dc297** [comment]
Hey yes, I could return a JSON string in the variable value and the user can set up a simple JavaScript code to parse that JSON. 
The JSON string will have key-value pairs of the connection details like current_status, connected_to (this could be an array to handle multiple brokers)

I could maybe add events whenever the connection/disconnection to/from server happens.

Let me know what are your thoughts on this.

**Comment by ShaddyDC** [comment]
Seems alright to me.
I think there's an AutoTools JSON parser, which would make things pretty simple for users; though I haven't used it myself.
Besides that, this solution seems decent to me if you actually plan to support multiple brokers in the future.
But I'm not sure if it doesn't get a bit too complicated for a really simple use case. Maybe make it two different actions: one that gets data about all connections in the form of a JSON string and one that only gets the information about a specific connection that directly gives you a couple of useful variables.
The latter would probably be a lot easier to use in most cases (including mine), though I can see the merit of a solution to get information about all connections.
So yeah, I'd probably implement both and let the end-user choose.

**Comment by acefed** [comment]
Sounds like some epic work is needed to achieve all this, but it would be awesome indeed. I would split it up into seperate requests, making it easier to create, test and prioritise.

**Comment by dc297** [comment]
Hi
A simplified version is available in the latest version. Do check it out.

Cheers!

**Comment by deepessh** [comment]
Hey, I think most the work has been completed on this. Closing this for now. Please open new issues if you need any new features or you face any problems.
