### ISSUE TITLE
Touch interface going crazy on Fire 7

### ISSUE THREAD

**Issue by Bra1nK** [dc297/mqttclpro#12]
Had to uninstall the latest version from my Amazon Fire 7 as after a few minutes of use I start getting phantom inputs on the touch screen which make the tablet unusable. Restarting (with great difficulty) the tablet settles things down for a while but the issue soon returns. Thought I had a hardware problem initially but uninstalling your mqtt plug in fixed it.

**Comment by dc297** [comment]
Hey @Bra1nK 

Something like this should not happen by using the app since the app does not have any permission to control the touch.
Do you have any touch related task set up in tasker which might be causing this behavior?

Also, is it possible for you to share the logcat for that time.

Cheers
Deepesh

**Comment by Bra1nK** [comment]
I don't have any touch related tasks set up in tasker, this issue only came about following the last update (jellybean support added). It would be difficult to get a logcat as reinstalling the app makes the tablet unusable. The fire 7 has been rooted to remove the Amazon ads etc that come with the cheap version.

**Comment by dc297** [comment]
Which android version are you on?

**Comment by Bra1nK** [comment]
I believe it's Android 5.1.2 (Lollipop) as that was the latest rootable version when I got the tablet although it's difficult to be certain as I can't find anywhere it's displayed.

**Comment by dc297** [comment]
Do you have a file explorer installed on the tablet. You could take a look at the build.prop file in /system/ and find the property named ro.build.version.sdk. This will tell us the exact android version you are on.

Have you flashed any custom ROM? Did you download the application from the play store?

**Comment by Bra1nK** [comment]
ro.build.version.sdk=22, I haven't flashed a custom ROM and MQTT client came from the play store.

**Comment by dc297** [comment]
Let me test on an emulator with android version 5.1

**Comment by Bra1nK** [comment]
OK bear in mind this is Amazon's slightly bastardised version and it takes 10 mins or so before the touch interface starts its shenanigans initially.

**Comment by dc297** [comment]
Hey @Bra1nK 

Do you have anything setup in tasker related to the plugin? Or just installing the app causes the issue?

**Comment by Bra1nK** [comment]
Yes tasker is set to play a notify sound when it receives a message of 'Ring' on the topic 'Doorbell' I've not tried it without a tasker process.

**Comment by Bra1nK** [comment]
Happened again this morning but obviously nothing to do with MQTT client as it's still uninstalled so I'm back to thinking it's an unrelated and occasional hardware issue so I'll close this. Sorry if I've wasted your time but it's taken over a week for the issue to reoccur since I uninstalled your MQTT client, I'm now thinking it's something to do with my granddaughters use of the tablet on babysitting weekends.

**Comment by dc297** [comment]
Hi @Bra1nK 

Not a problem. Sorry to hear that it was a hardware issue.
