### ISSUE TITLE
No message when screen are locked/off.

### ISSUE THREAD

**Issue by purjolini** [dc297/mqttclpro#13]
The message is received only when the phone are unlocked. I have a Nexus 5 with Android  7.1.
I've tried disable battery optimization for MQTT client. I want to use it with tasker action. So kind of need to receive messages when screen are off. Thanks for any help.

**Comment by dc297** [comment]
Hey, the app should receive messages even when the screen is off. Are you using any other battery saving features which might be killing the app?

**Comment by purjolini** [comment]
None, battery savings apps at all. Only the built in. But exluded both tasker and MQTT client. I've also tried with HTC one play editon with Android 5.1, same thing only receive message when screen is on. But I tried with an old Samsung GT-I9210T with cyanogen rom android version 4.4.3. On the samsung it works.

**Comment by dc297** [comment]
Hey

I have been using the app on Oneplus One on Lineage OS 7.1.1. I don't face any such issue on my device. 
Can you share details of your configuration?

Cheers

**Comment by purjolini** [comment]
Update. Did a factory reset on the HTC One. And now it's working. I've tried only reset data and reinstall both tasker and MQTT client on Nexus 6p. Didn't work. So I guess I need a factory reset there too. I think it have something to do with tasker. Not MQTT client. The configure I tried was Profile if event MQTT client receive message Topic: smarthome/tv message:tv = Task alert "Beep".

**Comment by dc297** [comment]
Hey I hope that this issue is resolved. I am going to close it for now. You may reopen it if you face the issue again.
