### ISSUE TITLE
Crashes if URL string contains protocol prefix

### ISSUE THREAD

**Issue by trisk** [dc297/mqttclpro#15]
The app crashes if I put "ws:/host" or anything other than a bare hostname in the "URL" field, which is confusing when the field is titled "URL".

**Comment by dc297** [comment]
Hey @trisk 

Thanx for using the app and raising the issue.

I have handled this in the code. The app should not crash if you put protocol in the URL. Can you share what exactly are you putting in the field so that I can try to simulate the issue.

**Comment by trisk** [comment]
I using "ws:/hass" (for my Home Assistant host running an hbmqtt instance) and had Websocket checked. This is with the current version on Google Play. The app crashes immediately after startup until I clear data.

**Comment by dc297** [comment]
Hey I have fixed this issue. Will be pushing the update to google play soon.

**Comment by dc297** [comment]
Hey i have pushed the new update. Do let me know if the issue is fixed.

**Comment by trisk** [comment]
Ah, yes, this issue is indeed fixed (updating stopped the crash on startup), thanks.

(btw, I installed mosquitto but haven't gotten around to replicating the other issue yet.)
