### ISSUE TITLE
Changing in using certificate anfroid 7

### ISSUE THREAD

**Issue by Sellig28** [dc297/mqttclpro#16]
Hi,
I use ssl connexion but since android 7 there are some updates.
Android Keystore for self signed certificate is no more used for android apps.
Could you update your app to select an android certificate authority with a certificate. All can be a p12 certificate.

Thank you.
Sellig28.

**Comment by dc297** [comment]
Hey

This is one of the planned features. Can't assure of the timeline.

Cheers
Deepesh

**Comment by dc297** [comment]
hey I am starting work on this issue. Opened a new issue for the same. https://github.com/dc297/mqttclpro/issues/28
