### ISSUE TITLE
Unable to publish empty (null) message

### ISSUE THREAD

**Issue by acefed** [dc297/mqttclpro#17]
In order to remove an old obsolete retained message on a mosquitto broker topic, I tried to send a new retained message with an empty (NULL) payload to the topic in case, as was suggested on the mosquitto mailinglist. Sending this message with a mosquitto_pub client works as intended and removes the retained message from the topic.

I can't seem to publish an empty message with mqttclpro MQTT Client. If I enter the topic without a message, the pub topic isn't stored, resulting in a missing configuration. If I edit an existing pub config and remove the message, the change isn't stored in the config.

I think fixing/changing this would improve the plugin, making MQTT more "payload agnostic", while adding the support of retained message removal this way.

PS: This plugin is awesome, thanks a lot for your great work!

**Comment by dc297** [comment]
Hey..Thanx for using the plugin.

I don't know how I missed it. Will add in upcoming version.

Cheers
Deepesh

**Comment by acefed** [comment]
Tnx, that's great. Keep up the good work :)

**Comment by dc297** [comment]
Hey the issue should be fixed in the latest version. Do check it out and let me know.

**Comment by acefed** [comment]
Great stuff... Tested: OK!
Samsung Galaxy S6, Android 7.0, Tasker v5.0u4, MQTT Client 2.2.2

I am now able to store an empty message, which results in publishing a (null) message. A DAY after reporting the issue.

PS: Donated a beer (or two milks) because you ROCK certified, sir o/

**Comment by dc297** [comment]
Great! Thanx for the beer! Cheers!
