### ISSUE TITLE
Tasker reports (a lot of) missing icon warnings in log

### ISSUE THREAD

**Issue by acefed** [dc297/mqttclpro#18]
When opening Tasker, I am frequently welcomed with a bunch of log entry warnings reporting a missing icon reference in mqttclpro, see screenshot below. Current version does this, and so did the previous version which was the first version I installed.

Currently using Samsung Galaxy S6, Android 7.0, Tasker v5.0u4, MQTT Client 2.2.2

Not sure if I'm missing something in the interface, the plugin functionality seems normal.

![screenshot_20170822-084811](https://user-images.githubusercontent.com/13823728/29583206-9f467de8-877f-11e7-9a5d-774afefe77b9.jpg)

**Comment by dc297** [comment]
Hi

Should be fixed in the latest version.

Cheers!
Deepesh

**Comment by acefed** [comment]
Awesomesauce, thanks!
