### ISSUE TITLE
[UX improvement] Setting/using variable names

### ISSUE THREAD

**Issue by acefed** [dc297/mqttclpro#21]
After a lot of trial and error, and digging through old github issues, I managed to set received MQTT messages as Tasker variables, which works perfectly by the way in mqttclpro.  The current "tooltip" says:

"Message tasker variable name"

My first failures resulted from:
1) including the % in the name (like Tasker and other plugins usually do)
2) trying uppercase (global) variable names, while only lowercase (local) var names are allowed

Reading old issues, other users seem to have met similar problems when trying mqttclpro for the first time. This increases the learning curve, and could probably easily be improved. My suggestion for improvement:

1) include the % when setting the variable in mqttclpro (imho more consistent with other Tasker usage);
2) explain the restriction on the use of lower case var names;
3) add an example or perhaps default var name

Combined, this results in a "tooltip" along the lines of:

"Tasker variable name in lowercase, i.e. %varmqtt", or
"Lowercase Tasker variable name, i.e. %varmqtt"

Without implementing (1), this would of course render as:

"Tasker variable name in lowercase, i.e. varmqtt", or
"Lowercase Tasker variable name, i.e. varmqtt"

Hope this helps.

**Comment by dc297** [comment]
Hey Thanx a lot for the suggestion.

Yes, this makes more sense. I have pushed the changes to Play. Do check it out and more UX improvement related suggestions are welcome.

Cheers!
Deepesh

**Comment by acefed** [comment]
Is "varmqtt" the new tooltip text?

If so, this doesn't give the user much information either. But hey, if it functions as a usable default, decreases user errors, and shortens their learning curve, it is an improvement. Time will tell, users can be unpredictable :)
