### ISSUE TITLE
[UX improvement] Display full topic names in subscription list view

### ISSUE THREAD

**Issue by acefed** [dc297/mqttclpro#22]
When the MQTT Client app mqttclpro is started/opened, a list of current subscriptions is visible. Topic names are truncated at 20-ish characters, because these names usually take up more space than the screen offers. So far so good.

I haven't found any way to access the full topic names on this screen. Which is a problem, when the first part (20-ish characters) of topics are the same, as there is no way to select the specific topic a user is looking for. In my case, the first part is quite generic, and identical on many topics. The specific differences in topics are in the last part, out of view. This introduces problems when deleting a topic.

Hey, when rotating the device from portrait to landscape, more screen estate is available. This could offer more characters to be displayed, and better information on topic names. Unfortunately, this has no effect on truncation, but results in more visible unused whitespace.

The detailed view after clicking on the topic does not have this restriction, but a topic without a message has no detailed view. A click on the topic only flashes "No messages received." briefly.
To be able to delete a certain topic subscription from the list, I have to publish a specific message to that topic, after which I can identify the topic, and then delete it. This leaves room for improvement in usability/user friendliness.

Apart from 1) using the available screen estate better in horizontal/landscape mode, and 2) allow a detailed view for topics without messages, I don't know the ultimate solution for this. Many apps use scrolling text, automatically or manual, to allow access to offscreen text. Not sure if that's doable at all, or the way to go here.

**Comment by dc297** [comment]
Did some UI/UX improvements. Do checkout the latest update.

Cheers!

**Comment by acefed** [comment]
That's a perfect solution, sir. Couldn't think of a nicer way to handle this... no additional user clicks necessary the get to the required information. Scrolling when needed (portrait view), using the screen estate when possible (landscape view). Best of both worlds. Fixed like a true pro 👍

Thanks & keep up the good work!
