### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by brianmay** [dc297/mqttclpro#23]
Hello,

There is no license associated with this, which makes it default to "All rights reserved." plus some exceptions for GitHUB, as per their ToS.

As I believe the intention was to make this open source software, can you please give it an open source license?

https://help.github.com/articles/licensing-a-repository/

Thanks

**Comment by brianmay** [comment]
Please also tag the releases in git. Makes it possible to see how much has changed since the last release...

**Comment by dc297** [comment]
Yeah I have been too lazy to add those. Will add soon.

**Comment by dc297** [comment]
Added license.
