### ISSUE TITLE
Tasker message topic variabile needed

### ISSUE THREAD

**Issue by p3g4asus** [dc297/mqttclpro#25]
Actually when a tasker event is fired,there is no chance to know what was the topic of the message that caused the event but only its payload. Knowing the actual topic string is required because the generating subscription could have wildcards (. or #).  I think this should be rather easy to implement. Maybe just adding few lines of code in QueryReceiver.java and a variable name choosing line in the tasker event UI.

**Comment by dc297** [comment]
Done. Checkout the new update.

Cheers!

**Comment by dc297** [comment]
closing as added.
