### ISSUE TITLE
incoming message ignored if tasker still processing previous message

### ISSUE THREAD

**Issue by brianmay** [dc297/mqttclpro#27]
If an incoming message is received before Tasker is finished processing the old message (e.g. two messages received at the same time), the new message will get logged and then ignored. Ideally it should be queued and processed after Tasker has finished processing the first message.

At least this appears to be what is happening. I delayed a task from exiting, and tried sending new incoming messages.The same results. If you want me to gather any more evidence or retry that test - to double check my findings, I can do so.

**Comment by dc297** [comment]
I am able to simulate the issue. Though I am not sure if this a tasker limitation or issue. Let me dig some more into tasker documentation and see if it is possible.

Cheers!

**Comment by dc297** [comment]
Hey

I have reasons to believe that this is a tasker limitation. Can you confirm by testing for some other event? For example I tried for Shake event.

Cheers!

**Comment by brianmay** [comment]
Yes, was wondering if it was a tasker limitation. What are your expected results for testing other events? The same problem?

Is it possible to queue events up if tasker is busy? Or is this also a tasker limitation?

**Comment by dc297** [comment]
Yes, I faced the same problem. 

I have created a new discussion on tasker google group. https://groups.google.com/forum/#!topic/taskerdev/cX41TigklYA

**Comment by brianmay** [comment]
Thanks!

**Comment by dc297** [comment]
Hey, I just received a reply from Pent. Try the following:

In the task edit screen, select the settings menu item, for 'Collision Handling' (i.e. when the task is
running when a new copy of it is received) select whatever is
most appropriate.

You need to disable the beginner mode for the settings icon to be visible.

Cheers!

**Comment by brianmay** [comment]
Interesting... Not sure I understand exactly how it works in various situations just yet (e.g. do two distinct tasks collide? subtasks?) however this does look like just what I am looking for.

Now to see what strange effects I get when running two copies of my task at once... Ideally, one task would wait for the other, but I can see (yet!) any easy way of doing this.

Anyway, closing this on the assumption that it will fix the problem.

Thanks!

**Comment by brianmay** [comment]
Hmmm. If I understand this discussion correctly, tasker only supports running one task at a time, so it might actually do what I want it to do anyway. https://groups.google.com/forum/#!topic/tasker/DSkNsXpaRs4

**Comment by brianmay** [comment]
Actually, this probably explains it better (and I suspect it applies here too even though they were discussing subtasks):

> If you set the priority lower than the current task, the current task will
> finish before the new one starts.
>
> If you set the priority higher than the current task, the new task will
> completely execute before the current one resumes.
>
> If the priorities are the same, the two tasks will take turns executing
> actions.

http://grokbase.com/t/gg/tasker/134384p4ca/perform-task-doesnt-wait-for-child-task-to-end-can-it

**Comment by dc297** [comment]
Yes, but how do you set priorities for copies of same task?

In our case, multiple instances of task will run simultaneously.

**Comment by brianmay** [comment]
My early testing suggests that multiple tasks started from mqttclpro do run in sequence. Which is something I wasn't actually expecting and don't understand either.

I believe It is possible to start a subtask at any stage, and override the priority.

Also of significance, I don't believe the collision handling has any affect on subtasks.
