### ISSUE TITLE
Add Support for Self-Signed SSL certificate

### ISSUE THREAD

**Issue by dc297** [dc297/mqttclpro#28]

**Comment by dc297** [comment]
@Sellig28 @Pengman

Please check out the latest update. I have added support for Self signed SSL certificates.

Cheers!

**Comment by Pengman** [comment]
This version connects after I provided the CA certificate, so thats great. Thanks for the quick fix.

**Comment by dc297** [comment]
can you test for client certificate auth as well?

**Comment by Sellig28** [comment]
Hi, 
I test it with only certificate authority and it's working. If I try with a client certificate, it's not working.
But let me test if I'm wrong. Normally not as I cans use owntracks with client authentication.

Some more features:
Have the possibility to choose a destination for certificate. We can't go in external sdcard even if it's less secured. giving a p12 certificate will be much appreciated as with almost one file you can have, ca + crt +key.

I 'll test more with clientcertificate and tell you.

**Comment by Sellig28** [comment]
So I confirm that if I'm using owntracks with client authentication it's working with my mosquitto server. The difference is that's a p12 certificate, but with same crt, key and ca inside.
So there's a client certificate pb. Pengman, you confirm ?

**Comment by Sellig28** [comment]
Oh, more information I use TLS1.2 but it's ok for a connection with only a CA.

**Comment by dc297** [comment]
Hey thanx for the feedback. Can you share your mosquitto.conf file? That would really speed up the work.

Also, I'll look into adding support for p12 files.

Cheers!

**Comment by Sellig28** [comment]
I use self signed certificate only and have my own CA.

first in mosquitto.conf:
`
# allow_anonymous false
autosave_interval 1800

connection_messages true
log_dest stderr
log_dest topic
log_type error
log_type warning
log_type notice
log_type information
log_type all
log_type debug
log_timestamp true
log_dest file /var/log/mosquitto/mosquitto.log
include_dir /etc/mosquitto/conf.d
pid_file /var/run/mosquitto.pid
user mosquitto

#message_size_limit 10240

password_file /etc/mosquitto/passwd
#acl_file jp.acl

persistence false
persistence_location /etc/mosquitto/
persistence_file mosquitto.db
persistent_client_expiration 1m

#pid_file xxxx

#for internal test if needed
#listener 1883
`

then in conf.d for everything ssl:
`
listener 8883
cafile /etc/mosquitto/ca_certificates/ca.crt
certfile /etc/mosquitto/certs/mosquitto.crt
keyfile /etc/mosquitto/certs/mosquitto.key
require_certificate true
tls_version tlsv1.2
`

for p12 files, it's a good idea As it was used in android and other places like openvpn ,etc ....

If you need more tel me.

Cheers.

**Comment by dc297** [comment]
Hey

The client certificate and client key issue should be fixed now. I have also added support for p12 files.
You may now store client certificate and key in p12 file.

Cheers!
Deepesh

**Comment by Sellig28** [comment]
Hi,
Sorry for my late answer, i was busy last time.

I try p12 files and it's working very well, thank you. Just one more information if you have time later. It's possible to put in p12: ca.crt, then client crt and key. In just one file you can have all.

It's not an emergency but more a feature.

Really thank you for that.

**Comment by deepessh** [comment]
Closing as a way to use SSL has been added.
