### ISSUE TITLE
Failure to Reconnect

### ISSUE THREAD

**Issue by Bra1nK** [dc297/mqttclpro#3]
Frequently, after being away from home or after the phone has 'slept' overnight the MQTT client loses connection and fails to reconnect until I reopen the client on my phone.

**Comment by dc297** [comment]
Are you using any memory or battery saving apps which might be killing the application? The app should attempt to reconnect automatically whenever the connection changes.

**Comment by Bra1nK** [comment]
Not that I'm aware of, just the standard android stuff (Android 6.01 on Samsung S7 Edge). It happened a couple of times during the day whilst I was in and yesterday. I have noticed, when I had tasker monitoring my WiFi connection, that my phone would periodically reconnect to the WiFi so presumably the MQTT client is failing to reconnect at times.

**Comment by Bra1nK** [comment]
Tried it just now and MQTT Client Tasker Plugin failed to receive the MQTT messages till I opened it but even then Tasker didn't get notified and wouldn't until I went into the Plugin settings via Tasker and saved without changing anything. The it proceeded to work normally.

**Comment by Bra1nK** [comment]
I've noticed the same task/plugin running on my Amazon Fire tablet doesn't appear to lose connection so following you comment above I'm wondering if it's something to do with Android 6.01's standard battery saving processes. I've disabled battery saving for the MQTT Client plugin and will report back (although the saving is only supposed to cut-in after 3 days of non-usage and it doesn't appear to affect Tasker)

**Comment by dc297** [comment]
I think I need to implement a connectivity change listener that should fix the problem for all devices.

**Comment by Bra1nK** [comment]
Disabling battery saving for the MQTT plug-in appears to have solved my  problem so I'll close the issue although I would ask that you add an icon (different to the standalone client) as tasker keeps complaining about the lack of one.

**Comment by dc297** [comment]
That's great. Yes I'll add an icon in the next version.
