### ISSUE TITLE
Messages lost when disconnected

### ISSUE THREAD

**Issue by mcspr** [dc297/mqttclpro#32]
I was experiencing some issues in connectivity to the broker, network connection periodically lost etc. And discovered that messages that triggered by the plugin during this time are simply lost.

Consider this test case:
1. Start up mosquitto broker somewhere in the lan
2. MQTT client app opened, configured. Top message says "connected to tcp://....."
3. Tasker task opened and tested that plugin delivers the message (via remote mosquitto_sub)
4. Restart mosquitto
5. Run the task test again. Toast shows up `Unable to publish as we are not connected`
6. Wait for reconnect timer. Try again. Message finally delivered.

This is in the logcat. Service correctly triggers reconnection ofcourse.
```--------- beginning of main
10-15 08:19:29.815 21255 21255 I db      : putting message
10-15 08:19:29.829 21255  3103 I mqttclpro: test/topic : 1 : 2 : false
10-15 08:19:29.850 21255  3103 I mqttclpro: scheduling next ping for Sun Oct 15 08:39:29 GMT+03:00 2017
10-15 08:19:35.934 21255  3106 I mqttclpro: Connecting...
10-15 08:19:35.948 21255  3106 W System.err: Не удается подключиться к серверу (32103) - java.net.ConnectException: Connection refused
10-15 08:19:35.948 21255  3106 W System.err:    at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:79)
10-15 08:19:35.948 21255  3106 W System.err:    at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
10-15 08:19:35.948 21255  3106 W System.err:    at java.lang.Thread.run(Thread.java:761)
10-15 08:19:35.948 21255  3106 W System.err: Caused by: java.net.ConnectException: Connection refused
10-15 08:19:35.948 21255  3106 W System.err:    at java.net.PlainSocketImpl.socketConnect(Native Method)
10-15 08:19:35.948 21255  3106 W System.err:    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
10-15 08:19:35.948 21255  3106 W System.err:    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
10-15 08:19:35.948 21255  3106 W System.err:    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
10-15 08:19:35.948 21255  3106 W System.err:    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
10-15 08:19:35.948 21255  3106 W System.err:    at java.net.Socket.connect(Socket.java:605)
10-15 08:19:35.948 21255  3106 W System.err:    at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)
10-15 08:19:35.949 21255  3106 W System.err:    ... 2 more
10-15 08:19:35.949 21255  3106 E mqttclpro: unable to connect192.168.100.55:1883 exception is Не удается подключиться к серверу
10-15 08:19:35.949 21255  3106 E mqttclpro: Не удается подключиться к серверу (32103) - java.net.ConnectException: Connection refused
10-15 08:19:35.949 21255  3106 E mqttclpro:     at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:79)
10-15 08:19:35.949 21255  3106 E mqttclpro:     at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
10-15 08:19:35.949 21255  3106 E mqttclpro:     at java.lang.Thread.run(Thread.java:761)
10-15 08:19:35.949 21255  3106 E mqttclpro: Caused by: java.net.ConnectException: Connection refused
10-15 08:19:35.949 21255  3106 E mqttclpro:     at java.net.PlainSocketImpl.socketConnect(Native Method)
10-15 08:19:35.949 21255  3106 E mqttclpro:     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
10-15 08:19:35.949 21255  3106 E mqttclpro:     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
10-15 08:19:35.949 21255  3106 E mqttclpro:     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
10-15 08:19:35.949 21255  3106 E mqttclpro:     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
10-15 08:19:35.949 21255  3106 E mqttclpro:     at java.net.Socket.connect(Socket.java:605)
10-15 08:19:35.949 21255  3106 E mqttclpro:     at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)
10-15 08:19:35.949 21255  3106 E mqttclpro:     ... 2 more
10-15 08:19:35.957 21255  3106 I mqttclpro: Scheduling next connect at Sun Oct 15 08:19:50 GMT+03:00 2017
10-15 08:19:39.905 21255 21255 I db      : putting message
10-15 08:19:39.919 21255  3083 I mqttclpro: test/topic : 1 : 2 : false
10-15 08:19:39.928 21255 21255 I mqttserv: Client ID: 1508023239468b58d80787
10-15 08:19:39.936 21255  3091 I mqttclpro: Connecting...
10-15 08:19:39.956 21255  3091 I mqttclpro: scheduling next ping for Sun Oct 15 08:39:39 GMT+03:00 2017
10-15 08:19:39.961 21255  3091 I mqttclpro: Successfully connected
10-15 08:19:39.961 21255  3091 I mqttclpro: Subscribing to all topics
10-15 08:19:39.963 21255  3091 I mqttclpro: [Ljava.lang.String;@5a57db8
10-15 08:19:39.967 21255  3091 I mqttclpro: scheduling next ping for Sun Oct 15 08:39:39 GMT+03:00 2017
10-15 08:19:46.684 21255 21255 I db      : putting message
10-15 08:19:46.704 21255  3106 I mqttclpro: test/topic : 1 : 2 : false
10-15 08:19:46.719 21255  3106 I mqttclpro: scheduling next ping for Sun Oct 15 08:39:46 GMT+03:00 2017
10-15 08:19:48.540 21255 21266 W SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/in.dc297.mqttclpro/databases/in.dc297.mqttclpro' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
10-15 08:19:48.540 21255 21266 W SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/in.dc297.mqttclpro/databases/in.dc297.mqttclpro' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
10-15 08:19:48.541 21255 21266 W SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/in.dc297.mqttclpro/databases/in.dc297.mqttclpro' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
10-15 08:19:50.998 21255 21292 I mqttclpro: Re-Connecting...
10-15 08:19:51.971 21255 21255 I db      : putting message
10-15 08:19:51.994 21255  3083 I mqttclpro: test/topic : 1 : 2 : false
10-15 08:19:52.024 21255  3083 I mqttclpro: scheduling next ping for Sun Oct 15 08:39:52 GMT+03:00 2017
```

I am too tinkering with mqtt application in java. `MqttDeliveryToken.getMessage()`, returned by the `MqttTopic.publish()`, may be considered to actually check for message status. At least for qos 1 or 2.
https://github.com/eclipse/paho.mqtt.java/blob/75594f0b226b14911f397b69059c18a50eaabb54/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/MqttDeliveryToken.java#L38-L45

Plus, `MqttClient` can itself store messages, if I am understanding this correctly:
https://github.com/eclipse/paho.mqtt.java/blob/75594f0b226b14911f397b69059c18a50eaabb54/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/MqttClient.java#L43-L58

(edited: code link to the comment, persistence)

**Comment by dc297** [comment]
Hey Thanx for raising the issue. I'll look into adding support for persistence.

Cheers!
Deepesh

**Comment by dc297** [comment]
Hey..so I looked into this issue.
Android Paho MQTT Client supports offline message buffer and persistence. But currently, in the code I am not using the Android version of the library.

I have been thinking of introducing multiple brokers for quite some time which would require a rewrite of the code. So, I have started working on a new version of the app which will support multiple brokers and code will be written as per latest specifications by Eclipse Paho.

Cheers!
Deepesh

**Comment by mcspr** [comment]
Great news!

Also, I've checked the paho java package once more. Funnily enough, here is actual offline persistence: https://github.com/eclipse/paho.mqtt.java/blob/75594f0b226b14911f397b69059c18a50eaabb54/org.eclipse.paho.client.mqttv3/src/main/java-templates/org/eclipse/paho/client/mqttv3/internal/ClientComms.java#L838

Enabled by using `MqttAsyncClient.setBufferOpts()` - every time client connects to broker it dumps buffered messages.

Tested that by not recreating `MQTTService.mqttClient` each reconnect, applying that buffer options to the internal `MqttClient.aClient` and running `MqttClient.setTimeToWait()` (`publish` locks things otherwise)

**Comment by dc297** [comment]
Correct!
But this will introduce more complexity in already complex code. That's why I thought it would be better to rewrite the app and have a simpler approach for things. Things like reconnector, pinger, offline buffer are pre-bundled into Pahe MQTT Client. At the same time it would be possible to introduce multiple brokers.

**Comment by dc297** [comment]
Hi

Offline message buffer is available in the latest beta release. Opt into beta channel here : https://play.google.com/apps/testing/in.dc297.mqttclpro.

Cheers!
Deepesh

**Comment by mcspr** [comment]
Hey. Just tested same thing with new build. Messages are successfully received! Should also probably test doze interaction.

**Comment by dc297** [comment]
Hey good to hear that it works. Please re-open if you find any issue. Also make sure you disable battery optimization before testing.
