### ISSUE TITLE
Multiple Brokers Support

### ISSUE THREAD

**Issue by dc297** [dc297/mqttclpro#33]
Hi Guys

@brianmay @mcspr @stipe76 @Sellig28 @Pengman @acefed @trisk @ShaddyDC

I have started working on Multiple Brokers support for MQTT Client. It will have all the features of the current version of MQTT Client. At the same time I am planning to update the underlying code on which the app works. The behavior of reconnector will change. Offline message buffer will be introduced. So, no more of that "Unable to publish...." toast. Overall, the code would be much simpler.

I am planning to start a beta channel on play store. So that it is easier to test the app and roll out bug free versions to production.

Let me know if you guys have any feature requests and if anybody would like to contribute.

I'll keep you guys posted on the progress.

Cheers!
Deepesh

**Comment by stipe76** [comment]
Great work mate

**Comment by acefed** [comment]
Nice. Nice. Nice! At the moment, I have no feature requests... I'm still catching up on all your previous work, updates, and additions :)

Tackling the "Unable to publish toast" is something I'm looking forward to. Serving lunch with my phone!
Seriously, testing improvements on that front is no problem.

I don't have/use multiple brokers (yet) myself.

**Comment by brianmay** [comment]
Multi-brokers does sound like an interesting feature to have. I have no immediate use for it, but when I do, this will considerably improve the usefulness of mqttclpro.

I have no feature requests that are within the scope of mqttclpro. Tasker on the other hand...

Actually did think of one feature request, will suggest in another bug report however.

**Comment by mcspr** [comment]
I have almost the same usecase, but slightly different than "real" multiple brokers - multiple urls for the same broker. Meaning, that the client tries connecting to each url listed top to bottom until it succeeds.

**Comment by dc297** [comment]
Hi Guys

I have added multiple broker support. Please opt into beta channel over here https://play.google.com/apps/testing/in.dc297.mqttclpro.

Feedback highly appreciated.

Cheers!
Deepesh

**Comment by dc297** [comment]
Hey guys I am closing this issue. Please create a new one if you face any issue. I'll be promoting this to production on 5th November 2017.
