### ISSUE TITLE
Autorestart after upgrades

### ISSUE THREAD

**Issue by brianmay** [dc297/mqttclpro#34]
I *think* this might be possible, but I have no idea how. As in I have not noticed this problem for other apps that need to be running constantly.

Currently after Google Playstore upgrades this app, it won't get restarted. Meaning events get lost.

I have turned off auto-updates for this app as a result, so I can manually restart after upgrading.

**Comment by dc297** [comment]
Yeah, seems like a required feature. I'll look into it.

**Comment by dc297** [comment]
Hi

This is available in the latest beta release. Opt into beta channel here : https://play.google.com/apps/testing/in.dc297.mqttclpro.

Cheers!
Deepesh
