### ISSUE TITLE
Unsubscribe from Beta version doesn't work

### ISSUE THREAD

**Issue by Bra1nK** [dc297/mqttclpro#35]
I registered for the beta version testing, decided I couldn't get on with it so unregistered, uninstalled and reinstalled from play store. A day or 2 later an update was flagged as available and lo and behold I was back on the beta again.

**Comment by dc297** [comment]
Hey Brian

Subscription for beta channel is maintained solely by Play Store. Ideally if you opt out, you should stop receiving beta updates. Can you try contacting Google play about that?

**Comment by dc297** [comment]
Also, can you share what issues were you facing while trying out the beta version? Because it will be the default version in a few days.
