### ISSUE TITLE
I only receive one update per app restart

### ISSUE THREAD

**Issue by RonnyAL** [dc297/mqttclpro#37]
Heya, and thanks for making a great app.

I wanted to use this as an efficient bridge between Tasker and Home Assistant. However, I'm having some trouble. I've successfully subscribed to a few topics (on cloudmqtt), and the app receives messages as expected once I subscribe. After the initial message, however, nothing happens until I force close and restart the app or reboot my phone.

I've tried manually publishing messages, but that didn't work either.

I'm on a Samsung Galaxy S7 Edge running (stock) Android 7. Any idea?

**Comment by dc297** [comment]
Hey

I have a few questions
1. Which version of the app are you using?
2. Did you disable battery optimization of the app?
3.  Can you check logcat?

Cheers!
Deepesh

**Comment by RonnyAL** [comment]
Thanks for getting back to me.

1. I am using version 3.2.1.
2. When I went to check just now, I accidentally hit some button that optimized 20 apps that weren't optimized already. Oops. Pretty sure MQTT Client would be among those 20 since I installed it yesterday, and Samsung only auto-optimizes if you haven't used an app for 3 days IIRC. Anyway - battery optimization was at least enabled after I accidentally hit that optimize button, so I went in and disabled it.
3. I wish. I definitely remember doing this before, but can't get it right this time. I'm (successfully) running logcat from cmd in Windows (using `adb logcat`) - but I'm unable to write the logcat to a file. Could you please help me with that?

Best Regards,
Ronny

**Comment by dc297** [comment]
Ohh..good to hear it worked.

Cheers!
