### ISSUE TITLE
MQTT 3.1.1 support?

### ISSUE THREAD

**Issue by agross** [dc297/mqttclpro#39]
The readme says MQTT 3.1 is supported. Is 3.1.1 also supported or support planned?

Background: [Home Assistant's embedded MQTT server](https://home-assistant.io/docs/mqtt/broker/) only appears to speak 3.1.1.

**Comment by deepessh** [comment]
Hey,

I have just pushed an update to play store. This should fix the issue with mqtt v3.1.1.

Cheers!

**Comment by agross** [comment]
Many thanks for the quick fix! It works now with Home Assistant!
