### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by oversc0re** [dc297/mqttclpro#4]
I can't connect to my server using MQTT Client for Tasker. It is not very likely to be a connection problem as I can connect to the same server with other apps (even with MQTT Client - standalone verson). 
I enter server settings (server uses username and password) and exit the settings screen, where I get a  "Failed to connect..." error. See the screenshot attached. 
Can I post any logs?

Regards, 
over. 
![image](https://cloud.githubusercontent.com/assets/6927565/21449416/6341dfa0-c8ed-11e6-97cf-522db4e84bc7.png)

**Comment by dc297** [comment]
Hi can you share broker details?

**Comment by oversc0re** [comment]
I am not very familiar with github. Is there a way to send it directly to you? I'd rather not publish my broker here.

**Comment by dc297** [comment]
can you send them on email?

**Comment by misterboo** [comment]
same here ... just can't connect ... the same broker works with the standalone version

**Comment by dc297** [comment]
The issue should be fixed in version 1.3. Please check and let me know. Thanx.

**Comment by misterboo** [comment]
Great! it is working now ;)

**Comment by oversc0re** [comment]
Problem resolved.

**Comment by Pengman** [comment]
I'm having this exact issue with current version. The standalone version (as well as other apps) works just fine. Is there a detailed log i can inspect to help troubleshooting?

**Comment by dc297** [comment]
Can you share your broker details?

**Comment by Pengman** [comment]
yeah, I should have included this in the first message.
Its a mosquitto server open to the internet on port 8883, not websockets.
I guess the most unusual part is that it is using a self-signed certificate that I added to my phone for SSL
my username is 7 characters and my password is 32 characters long

The exact same settings work for the standalone version

**Comment by dc297** [comment]
Ohh..Actually I have not tested the application for Self-Signed certificate yet. I am opening a new issue for the same. https://github.com/dc297/mqttclpro/issues/28
