### ISSUE TITLE
Events do not trigger Taster rules

### ISSUE THREAD

**Issue by fuslwusl** [dc297/mqttclpro#41]
Since last updated publishing messages via tasker action doesn't work - nothing gets sent.
Also received Mqtt events do not trigger Taster rules anymore.

**Comment by MyMothersHairdresser** [comment]
Same problem here. Literally even just trying to do an echo setup:

Mqtt client app subscribed to test/phone/echo
Tasker event, mqttclient, recieve message, on test/phone/echo, message variable is msg, topic variable is tpc, launches a Tasker task that:
- saves $msg into %ECHO variable
- popups with "its %msg"
- publishes %msg to the topic "test"

None of it does anything. Publishing to my broker's test/phone/echo from elsewhere is functional, but no tasker events are triggered, no popups, nothin.

**Comment by deepessh** [comment]
Hey

Please try setting up the events again. A lot of changes have been made to the core working of the app in order to enable multiple brokers and a lot of other features. Hope you like the new updated app.

Regards
Deepesh

**Comment by fuslwusl** [comment]
It works after reinstalling everything from scratch - I did the following steps:
1) Uninstall MQTT Client
2) Delete all triggers using MQTT Client Plugin
3) Restart device (to make sure Tasker is restarted)
4) Install MQTT Client (for tasker) and add broker credentials
5) Add topics in MQTT Client you want to listen to
6) Create the MQTT triggers in Tasker again

**Comment by mitchmb** [comment]
I had the same problem. The MQTT Client accepts all required messages. But Tasker will only receive some. I had to reinstall the older version 3.2.0. This is inapplicable.

**Comment by deepessh** [comment]
@fuslwusl Sorry for the hassle. But I hope the new features are useful to you.

@mitchmb Please open a new issue with details of the problems you are facing. Would love to fix them.
