### ISSUE TITLE
Text color white on white in topic dropdown

### ISSUE THREAD

**Issue by fuslwusl** [dc297/mqttclpro#43]
There is an issue with the text color in the dropdown where you can select the topic in tasker. 
On an older device with android 4.4.2 the text color is white (very very light gray) and the background is white too - so you cannot really read the topic.
On never devices everything is fine.
I know that this old device is not supported - but everything works fine so it would be great to see this minor bug fixed.
Thanx a lot!

**Comment by deepessh** [comment]
Cool. I'll fix it in the next update.

**Comment by deepessh** [comment]
should be fixed in version 4.2.4

**Comment by fuslwusl** [comment]
Perfect! Font ist now readable!
