### ISSUE TITLE
Constantly reconnecting

### ISSUE THREAD

**Issue by stipe76** [dc297/mqttclpro#44]
This is unusable for me now. The connection is lost and reconnects constantly, every second or so. Uninstalled and reinstalled. Rebooted phone. The last change lost all my previous data, and now can't stay connected

**Comment by stipe76** [comment]
That was a ClientID issue, mistake on my behalf. Apologies. I will see how it goes

**Comment by deepessh** [comment]
I did add a validation on client id. Let me check why this is happening.
