### ISSUE TITLE
Crash on start (tablet with android 4.4.2)

### ISSUE THREAD

**Issue by fuslwusl** [dc297/mqttclpro#49]
Hi, since a week or so the app crashes during start on android 4.4.2 tablet.
It worked without problems before - so it would be great it this old device was usable for mqtt again.
I know it is not on the supported device list - but it would be great if possible.
I sent you a crash report - hope this helps.

**Comment by deepessh** [comment]
Yeah, saw the crash report on play store. I don't have a KitKat device so it is not possible for me to test on KitKat. Currently trying to setup an emulator.

**Comment by deepessh** [comment]
should be fixed in app version 4.4.1

**Comment by fuslwusl** [comment]
Great - works like charm! Thanx a lot for the quick fix!
