### ISSUE TITLE
Publishing with Automate app doesn't work

### ISSUE THREAD

**Issue by fb22** [dc297/mqttclpro#50]
Hi,

I'm using the Android Automate app from LlamaLab and the MQTT client can be integrated as a plugin but I don't get messages published. The Automate app executes the plugin action and no error is shown in the log but the message doesn't appear in the MQTT client UI (subscribed to #).
I can publish messages in the MQTT client UI or subscribe to topics from other publishers.

**Comment by deepessh** [comment]
Hey hi

Thanx for opening the issue. I am able to publish messages using the automate app. Can you share what you are trying to do.

Regards
Deepesh

**Comment by fb22** [comment]
I'm trying to publish my location. For publishing I had used just the plug-in action block after a get location block and had defined just 1 variable 'lon'. In the plug-in action block I had selected 'Publish MQTT message' and selected my broker. Some name for topic and %lon for message.

**Comment by deepessh** [comment]
I am able to receive the location. Can you share a video or some screenshots on email?

**Comment by fb22** [comment]
I have got it running on another device but still no luck on the first device (exactly the same setup on both devices: only the plug-in block with a some data in it, so without the location block).
Any idea what may block it?
Good device: Nexus 4 with Lineage 14.1
Bad device: Mi6 with Miui 8.5 (stable)

**Comment by deepessh** [comment]
Hey, Sorry I don't have any Xiaomi device to test the app. Can you, however, check if the app works with tasker. Also, do you know of any emulators for MIUI?

**Comment by fb22** [comment]
Hi, my first attempt with Tasker was successful. And now Automate publish messages as well! If I kill and restart MQTT, I have to publish first a message with Tasker before Automate starts to publish. This behaviour is reproducible.

**Comment by deepessh** [comment]
I will be able to test as soon as I am able to get my hands on a Xiaomi phone. Maybe in the next 10-15 days.

**Comment by deepessh** [comment]
Hey,

So, I looked into the issue. You need to do the following for the app to work:

> You need to Provide permission of autostart to your app so that your app automatically start after every reboot.
>For that you have to do is just follow the process below
>go to security app>>permissions>>autostart

>Source: http://en.miui.com/thread-321535-1-1.html

Cheers!
Deepesh
