### ISSUE TITLE
Simultaneous messages confusion

### ISSUE THREAD

**Issue by brianmay** [dc297/mqttclpro#51]
I am getting some weird results that I can't really explain yet. It is possible I have got something wrong - I have only just woken up when this happens :-). I will update this as I get more details. I now seem to get different responses at times when multiple messages are received at the same time, such as:

* One message is ignored and the other message is processed twice.
* Once message is processed once and the other message is processed twice.
* Both messages are processed once as expected.

The log shows both messages received once as expected.

Will try to do more testing when I get a chance.

**Comment by deepessh** [comment]
Hey Brian

I have faced a similar issue whenever 3 or more messages are published within a time difference of ~10 ms.
Apparently, tasker is sending me same bundle multiple times. I am still looking into this. Will keep you posted.

Cheers!

**Comment by brianmay** [comment]
Glad to hear it. Thought I was losing sense of reality or something :-)

Sometimes (maybe around 75% of the time) some of the tasks don't get run, however the repeating of the last message (at least two times, sometimes possibly three, but not absolutely sure here) seems to be pretty consistent.

**Comment by brianmay** [comment]
After upgrading to Android 8.1.0 - which obviously required a reboot - this problem appears to have come good. I have no idea if it was the reboot or the upgrade did this, or how long this will last. Fingers crossed.

**Comment by brianmay** [comment]
It still happens that messages get duplicated, however is somewhat rare at the moment.

**Comment by deepessh** [comment]
@brianmay did you observe this behavior with the single broker version as well?

**Comment by brianmay** [comment]
I can't remember for sure. However, yes, I suspect problems only occurred after the update for the multiple broker version.

Unfortunately, seems to be hard to reproduce on demand :-(

**Comment by deepessh** [comment]
@brianmay I have made some changes in v4.4.3. Kindly monitor.

Thanx

**Comment by brianmay** [comment]
Deepesh Chaudhary <notifications@github.com> writes:

> @brianmay I have made some changes in v4.4.3. Kindly monitor.

Preliminary indications are hopeful, lets hope it stays that way...
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by brianmay** [comment]
Looks good still.

**Comment by deepessh** [comment]
That's great!

**Comment by deepessh** [comment]
Closing this.
