### ISSUE TITLE
"invalid topic"

### ISSUE THREAD

**Issue by henfri** [dc297/mqttclpro#58]
Hello,

thanks for this great app.
I did manage to add a task once, but when I do it again, I always get "Invalid topic", irrispective of what I add as a topic (e.g. varmqtttopic is test/opendoor and varmessage is 1.

What could be the reason?

Greetings,
Hendrik

**Comment by deepessh** [comment]
Have you subscribed to any topic for the broker? Please share a screenshot of the screen where you face this issue.

Cheers!
Deepesh

**Comment by henfri** [comment]
Hello Deepesh,

yes, I have. I think, I found the reason... I hit [Enter] before entering the topic, so I had an empty line before the actual string that I could not see.

Regards,
Hendrik

**Comment by deepessh** [comment]
Closing as resolved. Further improvements done in v4.4.5
