### ISSUE TITLE
Persistant Notification

### ISSUE THREAD

**Issue by dbrownpu** [dc297/mqttclpro#59]
When the Notification Priority is changed Persistent Notification becomes active even if previously off. The "Show Persistent Notification" toggle button will still show off and must be toggled ON and then back OFF to turn off the Persistent Notification.

**Comment by deepessh** [comment]
Hey, this should be fixed in v4.4.5 and above. Please test and let me know.

Cheers!

**Comment by deepessh** [comment]
Closing as fixed.
