### ISSUE TITLE
Doesn't work with CloudMQTT

### ISSUE THREAD

**Issue by Paragrimm** [dc297/mqttclpro#6]
Hey, thanks for your PlugIn! Sadly I can't use it with CloudMQTT, because I can't connect to the server. I suppose that it has something to do with Websockets?! Owntracks worked fine for me, but I used it to publish Position and Battery Level which is unnecessary with Tasker + a proper MQTT publishing PlugIn. Since yours was recently updated I hope that you can help here.

My Settings:
SSL: Off
URL: Server found in the CloudMQTT Console
Port: 1XXXX (first one, not the SSL, not the TSL/Websocket one)
Username: taskerSmartphone (as specified in CloudMQTT)
Password: as specified in CloudMQTT
Client ID: S3Neo

Payload:
{
"_type":"data",
"phone":%DEVID,
"battery":%BATT,
"bt":%BLUE,
"air":%AIR,
"wifi":%WIFI,
"date":%DATE,
"time":%TIME,
"freemem":%MEMF,
"gps":%GPS,
"silent":%SILENT,
"uptime":%UPS
}

In CloudMQTT my users (one for phone, one for tablet) have read and write set to true and the subscribed topic is: "devices/phone/#" for the phone and "devices/tablet/#" - I plan to publish to "devices/phone/sys/data".

Since I'm using Home Assistant on my Pi, I've a Home-Assistant User who subscribed everything (#) with Read/Write on true aswell. My Home Assistant MQTT Component should be configured correctly (the same way it worked with Owntracks).

I could set up Mosquitto or whatever on my pi, but CloudMQTT is more comfortable to me (and I'm a bit afraid that my Pi3 crashes or whatever... so I'm interested in "do everything possible externally, except it's more comfortable directly on the pi". But since I like the CloudMQTT pipeline... well, it would be nice, if it would work with your plugin :D.

Thanks for your help!

**Comment by dc297** [comment]
Hey Hi!

Yes, currently websockets is not supported. Let me take a look how I can add websockets support.

Cheers!

**Comment by Paragrimm** [comment]
Hey,

thank you very much! I hope that it'll work soon :).

**Comment by dc297** [comment]
Added in the latest version! Please test and let me know.

**Comment by dc297** [comment]
Closing as support added in latest version.

**Comment by patrik996** [comment]
Cloudmqtt does not work for me in your app. I have tried to turn on and off all settings, https, websockets, standard port, with and without clientid.

The app says Failed to connect to m21.cloudmqtt.com:14143. Next connect scheduled...

Cloud mqtt only logs this: 1503229475: New connection from xx.xxx.xxx.xxx on port 14143.

**Comment by dc297** [comment]
Hey

I just tried connecting to my own clowdmqtt free instance.

Have you created a custom user? If yes, have you setup rules for the user?

Cheers
Deepesh

**Comment by patrik996** [comment]
Hi!
I have not tested with the default account only custom user. I have setup ACL rules for the user(s) with Topic # so it should have all access. I have also tested to publish and subscribe from ubuntu, works fine.

Did you succeed in connecting to your own cloudmqtt instance? Maybe its something with my phone if it works for you.

**Comment by dc297** [comment]
Yes I am able to connect using my phone.

Is it possible for you to share the logcat for the time the connection fails?

Cheers
Deepesh

**Comment by dc297** [comment]
![image](https://user-images.githubusercontent.com/3163579/29513373-c30d9b1a-8682-11e7-928d-d562f4353e06.png)
this is my configuration.

**Comment by patrik996** [comment]
sorry, Im not familiar with logcat but it seems like you have to root your phone to use it. I have samsung knox on mine so can´t root it.

This is my cloudmqtt config:
![image](https://user-images.githubusercontent.com/15045710/29675979-17afc622-88f7-11e7-9d97-bb978736d85b.png)

**Comment by dc297** [comment]
Hey can you share your broker URL and username/pwd details with me via DM/Email?

It would be really helpful for me to resolve the issue faster. Maybe you can create a new user and remove it once I am done with testing.

Cheers
Deepesh

**Comment by patrik996** [comment]
Absolutely, I sent you an email just now.

Regards,
Patrik

**Comment by dc297** [comment]
Closing this issue as it's working fine.

**Comment by gracedotdotdot** [comment]
Hi,
 May I ask how do you guys resolve the issue: W/Mqtt: Failed to connect to: tcp://m14.cloudmqtt.com:37476MqttException (0) - java.net.UnknownHostException: Unable to resolve host "m14.cloudmqtt.com": No address associated with hostname?

Thanks,
Grace
