### ISSUE TITLE
Getting push notifications from topic

### ISSUE THREAD

**Issue by zoutepopcorn** [dc297/mqttclpro#61]
Is it possible to receive a push notification from a message?

Will Android allow it? Or just a toast. I m not a Android developer, but if it's not a hard job can take a look at it.

Thanks for the great app and for making it open source

**Comment by deepessh** [comment]
Hey, If you have tasker installed, you can set up an event to notify you whenever a message arrives.

The app in itself doesn't support notifying the user of message arrival.

EDIT: I'll suggest you to take a look at tasker. It'll open a whole new world of possibilities.
