### ISSUE TITLE
New update crashes after sleep

### ISSUE THREAD

**Issue by waraileron** [dc297/mqttclpro#62]
Hi there
I have been having connection issues on previous android version, currently the new update crashes after sleep.
Have submitted a crash report through google, not sure what other information can I give to facilitate the debugging.
Phone: Samsung S8, android 8.0.0 (oreo)
Edit: also point to note settings>notification now goes to stock notification setting bypassing the previous in app notification settings screen.
Edit 2: Crashes when using tasker task to publish*

**Comment by mcsinjak** [comment]
Hello.
I have the same problem after last update. Samsung galaxy S7 edge, android 8 stock.
Hope you'll fix it asap.

**Comment by deepessh** [comment]
Hey, this will be fixed in the next version.

EDIT: I have pushed the new update. Should be available in a few hours. Cheers!

**Comment by waraileron** [comment]
Cheers! Seems to be fixed, have a coffee on me.

**Comment by deepessh** [comment]
Thanks a lot. Cheers!
