### ISSUE TITLE
Persistent nofication vanishes when a MQTT message published from Tasker

### ISSUE THREAD

**Issue by dummylabs** [dc297/mqttclpro#64]
I have `Show Persistent Notification` setting on (with max priority) and I can see the icon and notification text in Android notification area. I have also disabled power optimizations in Android settings for MQTT Client. 
When I try to publish an MQTT message, the notification disappears weirdly though the message is sent successfully. And it seems that incoming MQTT messages still received by Tasker, no disconnection events catched.

Probably this is a minor issue as it does not affect main functionality but it may cause Android OS to close the app to reduce power consumption. 

Additional info:
I'm using Android 8.1.0 and the beta version of MQTT Client, but the same behavior confirmed for stable version too.

**Comment by deepessh** [comment]
Hey

I tested and am able to simulate the issue. Will be fixed in the next version.

Cheers!

**Comment by deepessh** [comment]
Hey, I have pushed the new update. Should be available in a few hours.

Cheers!

**Comment by jsetton** [comment]
I just installed the latest version 4.4.9 and when I try to go in any of the settings options, it brings me to the system app notifications for the mqtt client. Was this intended to be that way?

I am running the client on a Samsung S7 using Android 8.0.0.

**Comment by Bra1nK** [comment]
In my case it displays 'General' and 'Notifications' but neither icon does anything

**Comment by deepessh** [comment]
@jsetton thanks for pointing that out. It's a bug. Tapping on general should take you to the general settings screen. But tapping on Notifications will take you to the System notification settings screen if your android version is greater then Oreo.

@Bra1nK what's your android version?

**Comment by deepessh** [comment]
@jsetton this should be fixed in v4.5.0

**Comment by Bra1nK** [comment]
I'm on Android 8 0.0

**Comment by deepessh** [comment]
@Bra1nK should be fixed in 4.5.0

**Comment by deepessh** [comment]
Closing as fixed.
